### ISSUE TITLE
Clean Masters null pointer access violation

### ISSUE THREAD

**Issue by Ne0niq** [matortheeternal/zedit#130]
Hi, **matortheeternal**!
I tried to make big compilation of landscape mods using the zMerge 0.6.4, but I getting an error (please see the screenshot). I decided to post it just in case, maybe it may help to accumulate statistics of zMerge module.
![2019-05-25 17_06_14-zEdit - Progress](https://user-images.githubusercontent.com/47568939/58370511-2cd6f500-7f10-11e9-9646-38ae83224b3e.png)

**This error occurs every time when I try to use merge down improved method.**
**This error didn't occur when I used an old merge method and everything merges fine.**

Here is an ending of the merging log:
`[ERROR] Nebomir Modpack - Locations failed to build:
Error: Failed to clean masters in: Nebomir Modpack - Locations.esp
Access violation at address 0000000000000000 in module 'zEdit.exe'. Execution of address 0000000000000000
    at helpers.Fail (D:\Games\NeboMir\ZEdit\resources\app.asar\node_modules\xelib\lib\helpers.js:63:15)
    at Object.CleanMasters (D:\Games\NeboMir\ZEdit\resources\app.asar\node_modules\xelib\lib\masters.js:8:17)
    at Object.cleanMasters [as Clean] (file:///D:/Games/NeboMir/ZEdit/resources/app.asar/app/app.js:9430:15)
    at Object.removeMasters.merge [as removeMasters] (file:///D:/Games/NeboMir/ZEdit/resources/app.asar/app/app.js:9465:69)
    at finalizeMerge (file:///D:/Games/NeboMir/ZEdit/resources/app.asar/app/app.js:9133:28)
    at tryPromise (file:///D:/Games/NeboMir/ZEdit/resources/app.asar/app/app.js:9163:13)
    at action.then (file:///D:/Games/NeboMir/ZEdit/resources/app.asar/app/app.js:9047:17)
    at processQueue (D:\Games\NeboMir\ZEdit\resources\app.asar\node_modules\angular\angular.js:15616:28)
    at D:\Games\NeboMir\ZEdit\resources\app.asar\node_modules\angular\angular.js:15632:27
    at Scope.$eval (D:\Games\NeboMir\ZEdit\resources\app.asar\node_modules\angular\angular.js:16884:28)`
Here is a [full merging log](https://pastebin.com/FAJD9sWN) (it does not contain any other errors)

**Comment by matortheeternal** [comment]
This is a known issue with an unknown cause.  Thanks for making an issue for it.  :+1:

**Comment by kerrschtein** [comment]
Hi, I genuinely hate to necro things, but I seem to be having a similar issue:

![Screenshot_3](https://user-images.githubusercontent.com/55864549/89214860-94b5b080-d595-11ea-8dfa-6f2ad75ed653.png)

**Comment by matortheeternal** [comment]
If you encounter this issue just use the Clobber merge method.  This will most likely be fixed with updated version of xEdit codebase, and if not then when esper backend is introduced.
