### ISSUE TITLE
TypeError: Cannot read property 'getSection' of undefined

### ISSUE THREAD

**Issue by SleepyWanderer** [matortheeternal/zedit#150]
So I have no idea how to code really I just follow what ever a guide tells me to, hit enter and hope it works. I've been following https://thephoenixflavour.com/getting%20started/ This guide for modding my Skyrim SE and it requires me to use zEdit and Merge the Merge function (https://thephoenixflavour.com/guide/core/step-13/ ). Everything was fine up till the the build got to 95.7% and gave me this Error Log
```
[ERROR] Fixes [Merged] failed to build:
TypeError: Cannot read property 'getSection' of undefined
    at getIniValue (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:11243:27)
    at Object.getProfilePath (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:11318:29)
    at Object.getModList (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:11325:35)
    at disableMods (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:11332:31)
    at runIntegration (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9267:15)
    at Object.keys.forEach.key (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9313:13)
    at Array.forEach (<anonymous>)
    at Object.runIntegrations (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9311:40)
    at finalizeMerge (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9132:33)
    at tryPromise (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9163:13)
```

Full Log here 

```
================================================================================
Session started at Sun Aug 18 2019 14:47:38 GMT-0400 (Eastern Daylight Time)

Building merge Fixes [Merged]
Merge Folder: A:\Mode Organizer 2\mods\Fixes [Merged]
Merge Method: Clean
Unloading plugins
Loading Skyrim.esm (1/23)
Loading sandboxcylinderheight.esp (2/23)
Loading Move it Dammit - Less Wait Time and Follow Me Closer.esp (3/23)
Loading No More Standing Too Close SSE 1-0.esp (4/23)
Loading No NPC Greetings.esp (5/23)
Loading Update.esm (6/23)
Loading Dragonborn.esm (7/23)
Loading Raven Rock - Fix Exit on Horseback.esp (8/23)
Loading Dawnguard.esm (9/23)
Loading Dawnguard Dont Hunt Cured Vampires.esp (10/23)
Loading dD-No Spinning Death Animation Merged.esp (11/23)
Loading Don'tTalkWithYourMouthFull.esp (12/23)
Loading ChargeDialogueFix.esp (13/23)
Loading RaceScalingDisabled.esp (14/23)
Loading roadsidethief_simple_armor.esp (15/23)
Loading DawnguardVampireAttackFix.esp (16/23)
Loading Random Encounter Tweaks.esp (17/23)
Loading ImperialSoldiersEscortFix.esp (18/23)
Loading SparklesSE.esp (19/23)
Loading Hearthfires.esm (20/23)
Loading MannequinStayPut.esp (21/23)
Loading Runandwalkpaces.esp (22/23)
Loading Quiet Foxes.esp (23/23)
Done loading files.

Preparing merge...
============================================================
Merging into Fixes.esp
Added masters to merged plugin

Getting used FormIDs...
============================================================
Getting used FormIDs in sandboxcylinderheight.esp
Getting used FormIDs in Move it Dammit - Less Wait Time and Follow Me Closer.esp
Getting used FormIDs in No More Standing Too Close SSE 1-0.esp
Getting used FormIDs in No NPC Greetings.esp
Getting used FormIDs in Raven Rock - Fix Exit on Horseback.esp
Getting used FormIDs in Dawnguard Dont Hunt Cured Vampires.esp
Getting used FormIDs in dD-No Spinning Death Animation Merged.esp
Getting used FormIDs in Don'tTalkWithYourMouthFull.esp
Getting used FormIDs in ChargeDialogueFix.esp
Getting used FormIDs in RaceScalingDisabled.esp
Getting used FormIDs in roadsidethief_simple_armor.esp
Getting used FormIDs in DawnguardVampireAttackFix.esp
Getting used FormIDs in Random Encounter Tweaks.esp
Getting used FormIDs in ImperialSoldiersEscortFix.esp
Getting used FormIDs in SparklesSE.esp
Getting used FormIDs in MannequinStayPut.esp
Getting used FormIDs in Runandwalkpaces.esp
Getting used FormIDs in Quiet Foxes.esp

Copying records...
============================================================
Copying records from Quiet Foxes.esp
Copying records from Runandwalkpaces.esp
Copying records from MannequinStayPut.esp
Copying records from SparklesSE.esp
Copying records from ImperialSoldiersEscortFix.esp
Copying records from Random Encounter Tweaks.esp
Copying records from DawnguardVampireAttackFix.esp
Copying records from roadsidethief_simple_armor.esp
Copying records from RaceScalingDisabled.esp
Copying records from ChargeDialogueFix.esp
Copying records from Don'tTalkWithYourMouthFull.esp
Copying records from dD-No Spinning Death Animation Merged.esp
Copying records from Dawnguard Dont Hunt Cured Vampires.esp
Copying records from Raven Rock - Fix Exit on Horseback.esp
Copying records from No NPC Greetings.esp
Copying records from No More Standing Too Close SSE 1-0.esp
Copying records from Move it Dammit - Less Wait Time and Follow Me Closer.esp
Copying records from sandboxcylinderheight.esp

Refactoring references...
============================================================
Building references for Fixes.esp
Refactoring references to sandboxcylinderheight.esp
Refactoring references to Move it Dammit - Less Wait Time and Follow Me Closer.esp
Refactoring references to No More Standing Too Close SSE 1-0.esp
Refactoring references to No NPC Greetings.esp
Refactoring references to Raven Rock - Fix Exit on Horseback.esp
Refactoring references to Dawnguard Dont Hunt Cured Vampires.esp
Refactoring references to dD-No Spinning Death Animation Merged.esp
Refactoring references to Don'tTalkWithYourMouthFull.esp
Refactoring references to ChargeDialogueFix.esp
Refactoring references to RaceScalingDisabled.esp
Refactoring references to roadsidethief_simple_armor.esp
Refactoring references to DawnguardVampireAttackFix.esp
Refactoring references to Random Encounter Tweaks.esp
Refactoring references to ImperialSoldiersEscortFix.esp
Refactoring references to SparklesSE.esp
Refactoring references to MannequinStayPut.esp
Refactoring references to Runandwalkpaces.esp
Refactoring references to Quiet Foxes.esp

Handling asset files...
============================================================
Disabling merged plugins in plugins.txt
Unloading plugins
[ERROR] Fixes [Merged] failed to build:
TypeError: Cannot read property 'getSection' of undefined
    at getIniValue (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:11243:27)
    at Object.getProfilePath (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:11318:29)
    at Object.getModList (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:11325:35)
    at disableMods (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:11332:31)
    at runIntegration (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9267:15)
    at Object.keys.forEach.key (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9313:13)
    at Array.forEach (<anonymous>)
    at Object.runIntegrations (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9311:40)
    at finalizeMerge (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9132:33)
    at tryPromise (file:///A:/Skyrim%20Mods/Tools/zEdit/resources/app.asar/app/app.js:9163:13)
```

Sorry for any "misuse of lingo" no idea of what Im doing hopefully you can help. Thanks in advance! :D

**Comment by matortheeternal** [comment]
Disable the "disable mods" integration on the merging tab of the settings modal.
