### ISSUE TITLE
Access violation during clean step in merge

### ISSUE THREAD

**Issue by jlxsolutions** [matortheeternal/zedit#157]
[ERROR] houses failed to build:
Error: Failed to clean masters in: houses.esp
Access violation at address 0000000000000000 in module 'zEdit.exe'. Execution of address 0000000000000000
    at helpers.Fail (F:\games\skyrimtools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\xelib\lib\helpers.js:63:15)
    at Object.CleanMasters (F:\games\skyrimtools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\xelib\lib\masters.js:8:17)
    at Object.cleanMasters [as Clean] (file:///F:/games/skyrimtools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9441:15)
    at Object.removeMasters (file:///F:/games/skyrimtools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9476:69)
    at finalizeMerge (file:///F:/games/skyrimtools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9144:28)
    at file:///F:/games/skyrimtools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9174:13
    at file:///F:/games/skyrimtools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9058:17
    at processQueue (F:\games\skyrimtools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:15616:28)
    at F:\games\skyrimtools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:15632:27
    at Scope.$eval (F:\games\skyrimtools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:16884:28)

Access violation at address 0000000000000000 in module 'zEdit.exe'. Execution of address 0000000000000000
(0000000000252858){XEditLib.dll} [0000000000653858] JclDebug.JclCreateStackList + $48
(0000000000252767){XEditLib.dll} [0000000000653767] JclDebug.DoExceptionStackTrace + $77
(00000000002540D2){XEditLib.dll} [00000000006550D2] JclDebug.DoExceptNotify + $92
(0000000000245715){XEditLib.dll} [0000000000646715] JclHookExcept.TNotifierItem.DoNotify + $35
(000000000024595B){XEditLib.dll} [000000000064695B] JclHookExcept.DoExceptNotify + $BB
(0000000000245AFF){XEditLib.dll} [0000000000646AFF] JclHookExcept.HookedExceptObjProc + $2F
(000000000000EACE){XEditLib.dll} [000000000040FACE] System.@DelphiExceptionHandler + $26E
(00000000000A01FF){ntdll.dll   } [00007FFF3B6C11FF] Unknown function at __chkstk + $11F
(0000000000069289){ntdll.dll   } [00007FFF3B68A289] Unknown function at RtlRaiseException + $399
(000000000009EE6E){ntdll.dll   } [00007FFF3B6BFE6E] KiUserExceptionDispatcher + $2E

**Comment by matortheeternal** [comment]
switch merge method to clobber when this happens.

this is a known issue which requires updating the xEdit codebase to be fixed, currently hoping it will be resolved in the next major release.

**Comment by JSabelli-FDX** [comment]
This error still happens from time to time.
The temporary solution of switching to Clobber seems to still work.
