### ISSUE TITLE
Type error: Cannot read property '2' of null

### ISSUE THREAD

**Issue by nok1126** [matortheeternal/zedit#159]
I'm a newbie with this, but I follow all tutorial and when I want to merge some plugin it pop up this error. How to fix this? thank you very much.

Type error: Cannot read property '2' of null

full log:

================================================================================
Session started at Thu Nov 21 2019 01:15:49 GMT+0800 (台北標準時間)

Building merge Remodeled Armor - Vanilla Replacer-FF-Ver Merge
Merge Folder: G:\Mod Organizer 2 (2.2.1 Stable)\mods\Remodeled Armor - Vanilla Replacer-FF-Ver Merge
Merge Method: Clean
Unloading plugins
Loading Skyrim.esm (1/7)
Loading Update.esm (2/7)
Loading Dawnguard.esm (3/7)
Loading Dragonborn.esm (4/7)
Loading Remodeled Armor - Vanilla Replacer-FF-Ver.esp (5/7)
Loading Remodeled Armor - Vanilla Replacer - Dawnguard-FF-Ver.esp (6/7)
Loading Remodeled Armor - Vanilla Replacer - Dragonborn-FF-Ver.esp (7/7)
Done loading files.

Preparing merge...
============================================================
Unloading plugins
[ERROR] Remodeled Armor - Vanilla Replacer-FF-Ver Merge failed to build:
TypeError: Cannot read property '2' of null
    at Object.fh.getFileBase (file:///G:/Skyrim%20SE%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:129:55)
    at getMergeFileName (file:///G:/Skyrim%20SE%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9082:23)
    at prepareMergedPlugin (file:///G:/Skyrim%20SE%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9093:24)
    at file:///G:/Skyrim%20SE%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9119:13
    at file:///G:/Skyrim%20SE%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9058:17
    at processQueue (G:\Skyrim SE Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:15616:28)
    at G:\Skyrim SE Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:15632:27
    at Scope.$eval (G:\Skyrim SE Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:16884:28)
    at Scope.$digest (G:\Skyrim SE Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:16700:31)
    at Scope.$apply (G:\Skyrim SE Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:16992:24)

**Comment by matortheeternal** [comment]
`getMergeFileName` failed here, what is the filename you have entered for your merge?  Does it end in a valid extension like `.esp` ?

**Comment by NitzanHavoc** [comment]
@matortheeternal I've just had the same problem exactly (TypeError: Cannot read property '2' of null), and I did indeed forget to add ".esp" at the end of the new merged patch's name... probably happens when renaming using Ctrl+C -> Ctrl+V, human error :) Thanks for the heads up, helped me troubleshoot! And since I have the opportunity - thank you for everything you've done, are certainly soing and I hope will continue to do for the community! You are amazing on so many levels.

**Comment by SmashingQuasar** [comment]
Hey! ~~Where are we at with this? I get this error over 50% of the time I am trying to merge mods.~~

Edit: This only happens if you do not specify explicitly the extension of your merged file.

**Comment by shayna-lynn** [comment]
I'm getting this same error but no problems with file names/extensions. 
Merge name: ---- KIC + RWT Patches Merged
File name: KIC + RWT Patches Merged.esp

https://cdn.discordapp.com/attachments/602295703926079497/772585490205245500/Zmerge-error.png

Everything was fine until this specific merge then (((SPLAT)))
