### ISSUE TITLE
[ERROR] TypeError: Cannot read property 'edid' of undefined

### ISSUE THREAD

**Issue by avatarofevil** [matortheeternal/zedit#161]
I am attempting to build the patch using the patcher for [True Equipment Overhaul SE](https://www.nexusmods.com/skyrimspecialedition/mods/18157). It worked previously, but after the update to Skyrim SE to 1.5.97.0, it stopped working. The error it encounters is below (with specifics of the filepath before the zEdit directory removed):

```
[ERROR] TypeError: Cannot read property 'edid' of undefined
at getMatchingNamesArray (\zEdit_v0.6.5_-_Portable_x64\modules\teo\src\matchFinder.js:169:95)
at findMatch (\zEdit_v0.6.5_-_Portable_x64\modules\teo\src\matchFinder.js:273:22)
at Object.module.findExpandMatchForArmor (\zEdit_v0.6.5_-_Portable_x64\modules\teo\src\matchFinder.js:353:16)
at filter (\zEdit_v0.6.5_-_Portable_x64\modules\teo\src\patcher.js:404:37)
at Array.filter (<anonymous>)
at filterRecords (eval at value (/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:749:18), <anonymous>:546:39)
at getRecordsToPatch (eval at value (/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:749:18), <anonymous>:562:20)
at eval (eval at value (/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:749:18), <anonymous>:594:38)
at Array.forEach (<anonymous>)
at loadAndPatch (eval at value (/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:749:18), <anonymous>:593:26)
```

I have attached the logs generated by the failed patch. The same error appears each time in multiple attempts.
[app_log_anonymized.txt](https://github.com/z-edit/zedit/files/3883689/app_log_anonymized.txt)
[main_2019_11_23_22_01.txt](https://github.com/z-edit/zedit/files/3883690/main_2019_11_23_22_01.txt)
[progress_log_anonymized.txt](https://github.com/z-edit/zedit/files/3883691/progress_log_anonymized.txt)

**Comment by matortheeternal** [comment]
this issue is with the patcher's code.  please report it to DanielUA on his mod page.
