### ISSUE TITLE
Error when attempting manage patcher

### ISSUE THREAD

**Issue by PlanetMark1** [matortheeternal/zedit#180]
[INFO] zEdit v0.6.5 x64
[INFO] Initializing xelib with "I:\Fallout\1. z-Edit\XEditLib.dll"
[INFO] xelib v0.6.0.0 initialized successfully
[INFO] xelib working directory: "I:\Fallout\1. z-Edit\"
[INFO] Loading modules...
[INFO] Loading module unifiedPatchingFramework v1.5.1
[INFO] Modules loaded
[INFO] Loading deferred modules...
[INFO] Deferred modules loaded
[INFO] User selected profile: Fallout 4
[INFO] Using game mode: gmFO4
[INFO] DataPath: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\data\
[INFO] AppDataPath: C:\Users\Mark\AppData\Local\Fallout4\
[INFO] MyGamesPath: C:\Users\Mark\Documents\My Games\Fallout4\
[INFO] GameIniPath: C:\Users\Mark\Documents\My Games\Fallout4\Fallout4.ini
---------------------------------------------------------
***Error occurs when attmepting to manage patchers***
---------------------------------------------------------
[ERROR] TypeError: Cannot set property 'selected' of undefined
    at selectTab (eval at value (file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:749:18), <anonymous>:192:36)
    at new eval (eval at value (file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:749:18), <anonymous>:200:5)
    at Object.instantiate (I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:4640:14)
    at I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:9901:28
    at getController (file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:1866:16)
    at resolveController (file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:1875:24)
    at file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:1883:34
    at I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:7982:13
    at Scope.$eval (I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:16884:28)
    at Scope.$digest (I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:16700:31)
[ERROR] TypeError: Cannot set property 'selected' of undefined
    at selectTab (eval at value (file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:749:18), <anonymous>:192:36)
    at new eval (eval at value (file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:749:18), <anonymous>:200:5)
    at Object.instantiate (I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:4640:14)
    at I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:9901:28
    at getController (file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:1866:16)
    at resolveController (file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:1875:24)
    at file:///I:/Fallout/1.%20z-Edit/resources/app.asar/app/app.js:1883:34
    at I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:7982:13
    at Scope.$eval (I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:16884:28)
    at Scope.$digest (I:\Fallout\1. z-Edit\resources\app.asar\node_modules\angular\angular.js:16700:31)

**Comment by matortheeternal** [comment]
This is a known bug which is fixed in my development branch.  You can avoid it by opening the manage patchers modal by clicking the button in the title bar or from the right-click menu on the tree view, not from the button in the settings modal.
