### ISSUE TITLE
zMerge failed to build plugins 

### ISSUE THREAD

**Issue by alanktc** [matortheeternal/zedit#188]
It seems like zMerge failed to clean masters of the merged plugin

Unloading plugins
[ERROR] Places & Homes failed to build:
Error: Failed to clean masters in: Places & Homes.esp
Access violation at address 0000000000000000 in module 'zEdit.exe'. Execution of address 0000000000000000
(0000000000252858){XEditLib.dll} [0000000000653858] JclDebug.JclCreateStackList + $48
(0000000000252767){XEditLib.dll} [0000000000653767] JclDebug.DoExceptionStackTrace + $77
(00000000002540D2){XEditLib.dll} [00000000006550D2] JclDebug.DoExceptNotify + $92
(0000000000245715){XEditLib.dll} [0000000000646715] JclHookExcept.TNotifierItem.DoNotify + $35
(000000000024595B){XEditLib.dll} [000000000064695B] JclHookExcept.DoExceptNotify + $BB
(0000000000245AFF){XEditLib.dll} [0000000000646AFF] JclHookExcept.HookedExceptObjProc + $2F
(000000000000EACE){XEditLib.dll} [000000000040FACE] System.@DelphiExceptionHandler + $26E
(00000000000A01CF){ntdll.dll   } [00007FFF3D5C11CF] Unknown function at __chkstk + $11F
(0000000000069209){ntdll.dll   } [00007FFF3D58A209] Unknown function at RtlRaiseException + $399
(000000000009EE3E){ntdll.dll   } [00007FFF3D5BFE3E] KiUserExceptionDispatcher + $2E

    at helpers.Fail (D:\Games\Skyrim Mods\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\xelib\lib\helpers.js:63:15)
    at Object.CleanMasters (D:\Games\Skyrim Mods\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\xelib\lib\masters.js:8:17)
    at Object.cleanMasters [as Clean] (file:///D:/Games/Skyrim%20Mods/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9441:15)
    at Object.removeMasters (file:///D:/Games/Skyrim%20Mods/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9476:69)
    at finalizeMerge (file:///D:/Games/Skyrim%20Mods/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9144:28)
    at file:///D:/Games/Skyrim%20Mods/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9174:13
    at file:///D:/Games/Skyrim%20Mods/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9058:17
    at processQueue (D:\Games\Skyrim Mods\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:15616:28)
    at D:\Games\Skyrim Mods\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:15632:27
    at Scope.$eval (D:\Games\Skyrim Mods\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:16884:28)

**Comment by matortheeternal** [comment]
use clobber method
