### ISSUE TITLE
Access Violation in Xeditlib.dll using zMerge

### ISSUE THREAD

**Issue by MapMappening** [matortheeternal/zedit#194]
Just tryin' to merge some stuff when this appears.

`Fatal Error: Access violation at address 00000000005D06F7 in module 'XEditLib.dll'. Read of address 0000000000000000`
`Unloading Plugins`
`[ERROR] (Merge Patch) failed to build: There was a critical error during plugin/resource loading`

Doesn't matter what I do, this will always happen. This sort of access violation even happened in MergePlugins, so this is probably not a zEdit specific issue, but I want to make sure because I don't see this anywhere online. Launched using Mod Organizer 2.

EDIT: This also happens anywhere, not just zMerge. Doesn't matter which version I use either.

**Comment by kerrschtein** [comment]
I'm also having an access violation, though mine might be a different type:

[ERROR] CitiesnShit failed to build:
Error: Failed to clean masters in: CitiesnShit.esp
Access violation at address 0000000000000000 in module 'zEdit.exe'. Execution of address 0000000000000000
    at helpers.Fail (D:\Modding\Skyrim Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\xelib\lib\helpers.js:63:15)
    at Object.CleanMasters (D:\Modding\Skyrim Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\xelib\lib\masters.js:8:17)
    at Object.cleanMasters [as Clean] (file:///D:/Modding/Skyrim%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9441:15)
    at Object.removeMasters (file:///D:/Modding/Skyrim%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9476:69)
    at finalizeMerge (file:///D:/Modding/Skyrim%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9144:28)
    at file:///D:/Modding/Skyrim%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9174:13
    at file:///D:/Modding/Skyrim%20Tools/zEdit_v0.6.5_-_Portable_x64/resources/app.asar/app/app.js:9058:17
    at processQueue (D:\Modding\Skyrim Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:15616:28)
    at D:\Modding\Skyrim Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:15632:27
    at Scope.$eval (D:\Modding\Skyrim Tools\zEdit_v0.6.5_-_Portable_x64\resources\app.asar\node_modules\angular\angular.js:16884:28)

**Comment by matortheeternal** [comment]
@kerrschtein yours is a known issue, you either have to fix the unresolved references in the plugins you're merging or switch to the clobber merge method.

@MapAnon you have some kind of corrupt plugin file or something which is breaking the xEdit plugin loading code.  Make a new MO2 profile with no mods enabled and gradually enable mods until you find the culprit.  (or duplicate your current profile and gradually disable mods).  You can use zEdit to see if the error is happening instead of zMerge, if that makes it faster/easier.

**Comment by pavelhoral** [comment]
I have the same issue with the latest portable zEdit 0.6.7:

```
Loading resources from Fallout4 - Textures2.ba2
Fatal Error: Access violation at address 00000000005D1077 in module 'XEditLib.dll'. Read of address 0000000000000000
```

I am on Windows 11.

**Comment by GTTeancum** [comment]
I'm having the same issue as pavelhoral. I get an access violation error trying to extract from Fallout4 - Textures1.ba2. I'm also on Win 11.
