### ISSUE TITLE
"Maximum plugin count of 254 reached"

### ISSUE THREAD

**Issue by theCalcaholic** [matortheeternal/zedit#206]
When running a patcher (to be precise, the one from [ENB Light](https://www.nexusmods.com/skyrimspecialedition/mods/22574?tab=description)), I get this error message (paths shortened):

```
[ERROR] Error: Failed to create new element at: 0, "ENBLight Patch.esp"
Maximum plugin count of 254 reached.
    at helpers.Fail (\ZEdit\resources\app.asar\node_modules\xelib\lib\helpers.js:63:15)
    at \ZEdit\resources\app.asar\node_modules\xelib\lib\elements.js:37:21
    at helpers.GetHandle (\ZEdit\resources\app.asar\node_modules\xelib\lib\helpers.js:80:9)
    at Object.AddElement (\ZEdit\resources\app.asar\node_modules\xelib\lib\elements.js:35:20)
    at preparePatchFile (eval at value (file:////ZEdit/resources/app.asar/app/app.js:749:18), <anonymous>:672:35)
    at Object.run (eval at value (file:////ZEdit/resources/app.asar/app/app.js:749:18), <anonymous>:690:25)
    at build (eval at value (file:////ZEdit/resources/app.asar/app/app.js:749:18), <anonymous>:220:52)
    at Array.forEach (<anonymous>)
    at eval (eval at value (file:////ZEdit/resources/app.asar/app/app.js:749:18), <anonymous>:288:36)
    at Object.try (file:////ZEdit/resources/app.asar/app/app.js:10489:13)
```

I __do__ have more than 254 plugins - however, only if counting ESL flagged ones. Looks like zEdit counts them to the plugin limit...

**Comment by theCalcaholic** [comment]
Looking at the log message, I suppose, the issue is withing [xelib](https://github.com/z-edit/xelib).

**Comment by Drakonas** [comment]
zEdit in its current state forces all plugins, including ESL and ESP-FE, to count towards the plugin limit, due to it not being updated to support the new formats. Hopefully this gets fixed in the future, but I've just simply moved on after coming across the same issue 6 months ago. You'll have to limit the plugin count when making patches.

**Comment by eberkain** [comment]
man, thats a real bummer that this is still an issue.

**Comment by northumber** [comment]
Still an issue in 2025.
