### ISSUE TITLE
TypeError: Expected argument 3 to be a boolean

### ISSUE THREAD

**Issue by Glanzer-modder** [matortheeternal/zedit#235]
I upgraded from version 6.5.0 to 6.6.0 and got the following error when running the Spell Research Spell Tome Patcher. I tried it with version 6.6.1 and got the same error. I went back to version 6.5.0 and it finishes without errors.

[ERROR] TypeError: Expected argument 3 to be a boolean.
    at Object.SetFlag (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\xelib\src\js\elementValues.js:111:22)
    at patch (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:259:23)
    at eval (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:606:17)
    at Array.forEach (<anonymous>)
    at recordsAndPatch (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:604:20)
    at executeBlock (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:612:33)
    at Array.forEach (<anonymous>)
    at process (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:624:26)
    at Object.run (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:650:9)
    at eval (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:694:27)
[ERROR] TypeError: Expected argument 3 to be a boolean.
    at Object.SetFlag (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\xelib\src\js\elementValues.js:111:22)
    at patch (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:259:23)
    at eval (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:606:17)
    at Array.forEach (<anonymous>)
    at recordsAndPatch (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:604:20)
    at executeBlock (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:612:33)
    at Array.forEach (<anonymous>)
    at process (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:624:26)
    at Object.run (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:650:9)
    at eval (eval at value (file:///D:/Games/Utilities/zEdit/resources/app.asar/app/app.js:1:1), <anonymous>:694:27)

**Comment by Glanzer-modder** [comment]
This appeared in the app log which might be helpful for the debug.

[ERROR] Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: npc in value.npcs, Duplicate key: object:5487, Duplicate value: {"name":"_00EncFalmerF01MissileA [NPC_:244BAB56]","path":"_00EncFalmerF01MissileA","filename":"zPatch.esp","showNPCS":false}
https://errors.angularjs.org/1.8.2/ngRepeat/dupes?p0=npc%20in%20value.npcs&p1=object%3A5487&p2=%7B%22name%22%3A%22_00EncFalmerF01MissileA%20%5BNPC_%3A244BAB56%5D%22%2C%22path%22%3A%22_00EncFalmerF01MissileA%22%2C%22filename%22%3A%22zPatch.esp%22%2C%22showNPCS%22%3Afalse%7D
    at D:\Games\Utilities\zEdit\resources\app.asar\node_modules\angular\angular.js:138:12
    at ngRepeatAction (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\angular\angular.js:34028:21)
    at $watchCollectionAction (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\angular\angular.js:19130:13)
    at Scope.$digest (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\angular\angular.js:19270:23)
    at Scope.$apply (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\angular\angular.js:19630:24)
    at HTMLButtonElement.<anonymous> (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\angular\angular.js:29127:19)
    at defaultHandlerWrapper (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\angular\angular.js:3891:11)
    at HTMLButtonElement.eventHandler (D:\Games\Utilities\zEdit\resources\app.asar\node_modules\angular\angular.js:3879:9)

**Comment by matortheeternal** [comment]
Use v0.6.5 until patchers are updated.
