### ISSUE TITLE
scope[action] is not a function

### ISSUE THREAD

**Issue by Mrf2233** [matortheeternal/zedit#236]
0.6.6.1 opens by clicking on esp and it appears, even if it is re-extracted
[Window Title]
zEdit
[Content]
TypeError: scope[action] is not a function
    at trigger (file:///C:/Users/18284/Desktop/zEdit_v0/resources/app.asar/app/app.js:10921:66)
    at Scope.onTreeKeyDown (file:///C:/Users/18284/Desktop/zEdit_v0/resources/app.asar/app/app.js:10933:18)
    at fn (eval at compile (C:\Users\18284\Desktop\zEdit_v0\resources\app.asar\node_modules\angular\angular.js:16548:15), <anonymous>:4:237)
    at callback (C:\Users\18284\Desktop\zEdit_v0\resources\app.asar\node_modules\angular\angular.js:29123:13)
    at Scope.$eval (C:\Users\18284\Desktop\zEdit_v0\resources\app.asar\node_modules\angular\angular.js:19523:28)
    at Scope.$apply (C:\Users\18284\Desktop\zEdit_v0\resources\app.asar\node_modules\angular\angular.js:19622:25)
    at HTMLDivElement.<anonymous> (C:\Users\18284\Desktop\zEdit_v0\resources\app.asar\node_modules\angular\angular.js:29127:19)
    at defaultHandlerWrapper (C:\Users\18284\Desktop\zEdit_v0\resources\app.asar\node_modules\angular\angular.js:3891:11)
    at HTMLDivElement.eventHandler (C:\Users\18284\Desktop\zEdit_v0

**Comment by matortheeternal** [comment]
Will see if I can figure out what's causing this issue and resolve it, thanks for the report.
