### ISSUE TITLE
zMerge failing to merge despite proper filepaths. Outputs filepaths to zEdit itself,

### ISSUE THREAD

**Issue by Barerock** [matortheeternal/zedit#262]
![image](https://user-images.githubusercontent.com/38869993/147512469-c5b2ced2-60fc-412d-9e46-51fc4f1d2ae3.png)

I may have to edit this to load the image properly, but the error references a bunch of zEdit filepaths that don't relate to my mods at all. I have no idea why this is happening, as I've set up MO2 correctly, set the output correctly, and it can read things just fine. I admittedly am very not great at understanding any of this.

I am merging 31 armor mods. Not sure what other info I need to provide, as the program isn't giving me any I know how to use.

**Comment by Barerock** [comment]
I assume these each reference where an error has occurred, but I have no idea WHY, as all I've done is select the mods to merge, put them in a better load order, and pressed GO. Other than setting up the directory paths.

**Comment by matortheeternal** [comment]
Can you post the log please.  Merge built with errors is a message which is raised when something goes wrong, usually failing to remove a master when using the 'clean' merge method.  Try switching the merge method to clobber.

The 'paths' are what is called a 'stack trace', which actually references the code that was executing when the error is raised.  It is debug information which can be used by a developer to understand the context of an error.

**Comment by Barerock** [comment]
<details>
<summary>1st log today</summary>
================================================================================
Session started at Tue Dec 28 2021 13:36:51 GMT-0500 (Eastern Standard Time)


Building merge Armor Merge
Merge Folder: C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\merges\Armor Merge
Merge Method: Clean
Unloading plugins
Loading resources from Skyrim - Animations.bsa
Loading resources from Skyrim - Interface.bsa
Loading resources from Skyrim - Meshes0.bsa
Loading resources from Skyrim - Meshes1.bsa
Loading resources from Skyrim - Misc.bsa
Loading resources from Skyrim - Shaders.bsa
Loading resources from Skyrim - Sounds.bsa
Loading resources from Skyrim - Textures0.bsa
Loading resources from Skyrim - Textures1.bsa
Loading resources from Skyrim - Textures2.bsa
Loading resources from Skyrim - Textures3.bsa
Loading resources from Skyrim - Textures4.bsa
Loading resources from Skyrim - Textures5.bsa
Loading resources from Skyrim - Textures6.bsa
Loading resources from Skyrim - Textures7.bsa
Loading resources from Skyrim - Textures8.bsa
Loading resources from Skyrim - Voices_en0.bsa
Loading resources from AVExpansion.bsa
Loading resources from rugged_rogue - textures.bsa
Loading resources from rugged_rogue.bsa
Loading resources from wilderness_witch - Textures.bsa
Loading resources from wilderness_witch.bsa
Loading Skyrim.esm (1/26)
Loading Update.esm (2/26)
Loading Dawnguard.esm (3/26)
Loading HearthFires.esm (4/26)
Loading Dragonborn.esm (5/26)
Loading ScarletDawnArmor.esp (6/26)
Loading DCSorceress.esp (7/26)
Loading AnotherVampireLeatherArmor.esp (8/26)
Loading AVExpansion.esp (9/26)
Loading [Kirax] BDO Cavaro.esp (10/26)
Loading BDOR Armor collection by team tal.esp (11/26)
Loading DM BDOR Berserk by Team TAL.esp (12/26)
Loading DM BDOR Eclipse by Team TAL.esp (13/26)
Loading DM BDOR Hamshin by Team TAL.esp (14/26)
Loading DM BDOR Pack by Team TAL.esp (15/26)
Loading DR Alicia by Team TAL.esp (16/26)
Loading DX Necromancer Robes.esp (17/26)
Loading DX Succubus Armor.esp (18/26)
Loading Gigaduex_Outfit.esp (19/26)
Loading KMBikini.esp (20/26)
Loading KozakowyFalkaArmor.esp (21/26)
Loading LEKatarina.esp (22/26)
Loading rugged_rogue.esp (23/26)
Loading TBD - Sorceress.esp (24/26)
Loading TeraSuccubusArmor.esp (25/26)
Loading wilderness_witch.esp (26/26)
Done loading files.

Preparing merge...
============================================================
Merging into Armor Merge.esp
Added masters to merged plugin

Getting used FormIDs...
============================================================
Getting used FormIDs in ScarletDawnArmor.esp
Getting used FormIDs in DCSorceress.esp
Getting used FormIDs in AnotherVampireLeatherArmor.esp
Getting used FormIDs in AVExpansion.esp
Getting used FormIDs in [Kirax] BDO Cavaro.esp
Getting used FormIDs in BDOR Armor collection by team tal.esp
Getting used FormIDs in DM BDOR Berserk by Team TAL.esp
Getting used FormIDs in DM BDOR Eclipse by Team TAL.esp
Getting used FormIDs in DM BDOR Hamshin by Team TAL.esp
Getting used FormIDs in DM BDOR Pack by Team TAL.esp
Getting used FormIDs in DR Alicia by Team TAL.esp
Getting used FormIDs in DX Necromancer Robes.esp
Getting used FormIDs in DX Succubus Armor.esp
Getting used FormIDs in Gigaduex_Outfit.esp
Getting used FormIDs in KMBikini.esp
Getting used FormIDs in KozakowyFalkaArmor.esp
Getting used FormIDs in LEKatarina.esp
Getting used FormIDs in rugged_rogue.esp
Getting used FormIDs in TBD - Sorceress.esp
Getting used FormIDs in TeraSuccubusArmor.esp
Getting used FormIDs in wilderness_witch.esp

Copying records...
============================================================
Copying records from wilderness_witch.esp
Copying records from TeraSuccubusArmor.esp
Copying records from TBD - Sorceress.esp
Copying records from rugged_rogue.esp
Copying records from LEKatarina.esp
Copying records from KozakowyFalkaArmor.esp
Copying records from KMBikini.esp
Copying records from Gigaduex_Outfit.esp
Copying records from DX Succubus Armor.esp
Copying records from DX Necromancer Robes.esp
Copying records from DR Alicia by Team TAL.esp
Copying records from DM BDOR Pack by Team TAL.esp
Copying records from DM BDOR Hamshin by Team TAL.esp
Copying records from DM BDOR Eclipse by Team TAL.esp
Copying records from DM BDOR Berserk by Team TAL.esp
Copying records from BDOR Armor collection by team tal.esp
Copying records from [Kirax] BDO Cavaro.esp
Copying records from AVExpansion.esp
Copying records from AnotherVampireLeatherArmor.esp
Copying records from DCSorceress.esp
Copying records from ScarletDawnArmor.esp

Refactoring references...
============================================================
Building references for Armor Merge.esp
Refactoring references to ScarletDawnArmor.esp
Refactoring references to DCSorceress.esp
Refactoring references to AnotherVampireLeatherArmor.esp
Refactoring references to AVExpansion.esp
Refactoring references to [Kirax] BDO Cavaro.esp
Refactoring references to BDOR Armor collection by team tal.esp
Refactoring references to DM BDOR Berserk by Team TAL.esp
Refactoring references to DM BDOR Eclipse by Team TAL.esp
Refactoring references to DM BDOR Hamshin by Team TAL.esp
Refactoring references to DM BDOR Pack by Team TAL.esp
Refactoring references to DR Alicia by Team TAL.esp
Refactoring references to DX Necromancer Robes.esp
Refactoring references to DX Succubus Armor.esp
Refactoring references to Gigaduex_Outfit.esp
Refactoring references to KMBikini.esp
Refactoring references to KozakowyFalkaArmor.esp
Refactoring references to LEKatarina.esp
Refactoring references to rugged_rogue.esp
Refactoring references to TBD - Sorceress.esp
Refactoring references to TeraSuccubusArmor.esp
Refactoring references to wilderness_witch.esp

Handling asset files...
============================================================
Handling Bethesda Archive Files
Handling Face Data Files
Handling Extracted Files

Cleaning merge masters...
============================================================
[ERROR] Failed to remove master DCSorceress.esp.

Saving merge files...
============================================================
Saving merged plugin
Saving additional merge data
Unloading plugins
[ERROR] Armor Merge failed to build:
Error: Merge built with errors.
    at finalizeMerge (file:///C:/Users/LamSk/Desktop/Modding%20Tools%20Directory/ZEdit/resources/app.asar/app/app.js:9185:19)
    at file:///C:/Users/LamSk/Desktop/Modding%20Tools%20Directory/ZEdit/resources/app.asar/app/app.js:9212:13
    at file:///C:/Users/LamSk/Desktop/Modding%20Tools%20Directory/ZEdit/resources/app.asar/app/app.js:9090:17
    at processQueue (C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\resources\app.asar\node_modules\angular\angular.js:18075:37)
    at C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\resources\app.asar\node_modules\angular\angular.js:18123:27
    at Scope.$digest (C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\resources\app.asar\node_modules\angular\angular.js:19242:15)
    at Scope.$apply (C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\resources\app.asar\node_modules\angular\angular.js:19630:24)
    at C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\resources\app.asar\node_modules\angular\angular.js:21773:36
    at TaskTracker.completeTask (C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\resources\app.asar\node_modules\angular\angular.js:21403:7)
    at C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\resources\app.asar\node_modules\angular\angular.js:6879:19

Session terminated at Tue Dec 28 2021 14:00:14 GMT-0500 (Eastern Standard Time)
================================================================================



</details>

<details>
<summary>2nd log today</summary>
================================================================================
Session started at Tue Dec 28 2021 13:35:14 GMT-0500 (Eastern Standard Time)


Getting scripts to relink
============================================================
Loading scripts cache from C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\cache\scripts\scriptsCache.json
Loading archive cache from C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\cache\scripts\archiveCache.json
Caching archives
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\ccBGSSSE001-Fish.bsa
Caching 182 scripts
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\ccBGSSSE025-AdvDSGS.bsa
Caching 54 scripts
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\ccBGSSSE037-Curios.bsa
Caching 1 scripts
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\ccQDRSSE001-SurvivalMode.bsa
Caching 38 scripts
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\AVExpansion.bsa
Caching 0 scripts
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\rugged_rogue - textures.bsa
Caching 0 scripts
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\rugged_rogue.bsa
Caching 0 scripts
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\wilderness_witch - Textures.bsa
Caching 0 scripts
Caching scripts in archive C:\Steam\steamapps\common\Skyrim Special Edition\data\wilderness_witch.bsa
Caching 0 scripts
Caching loose scripts
Saving scripts cache
Saving archive cache

Building Form ID map
============================================================
Loading FormID map for Armor Merge
[WARN] Form ID map for Armor Merge not found at C:\Users\LamSk\Desktop\Modding Tools Directory\ZEdit\Armor Merge\merge\map.json

Relinking 0 scripts
============================================================

Session terminated at Tue Dec 28 2021 13:35:20 GMT-0500 (Eastern Standard Time)
================================================================================



</details>


I will try a clobber method, although I try to avoid those as they tend to break stuff in the long run. Thanks for the timely response over the holidays!

PS. sorry if the formatting is weird, I had a little fun forgetting the / on the ends of the summaries.

**Comment by Barerock** [comment]
A clobber _does_ work without any issue. I managed to get clean merges working on my other PC with nearly 40 armor mods. I am not competent with this stuff though, so it's probably quite obvious why it borked.
