### ISSUE TITLE
Hi I keep getting this error , I have tried reinstalls, older versions and loads of alternative types of merges. Am i missing something

### ISSUE THREAD

**Issue by Firewaterrunoff** [matortheeternal/zedit#273]
Edit 
ok update - it works if i uncheck disable plugins (disable mods was already unchecked)

Handling asset files...
============================================================
Handling Bethesda Archive Files
Handling Extracted Files
Disabling merged plugins in plugins.txt
Unloading plugins
[ERROR] Armour Merge 6 failed to build:
TypeError: Cannot read property 'split' of undefined
    at getNewPluginsText (file:///F:/Skyrim%20UVRE/tools/zEdit%20v0.6.6.1/resources/app.asar/app/app.js:9340:39)
    at disablePlugins (file:///F:/Skyrim%20UVRE/tools/zEdit%20v0.6.6.1/resources/app.asar/app/app.js:9353:23)
    at runIntegration (file:///F:/Skyrim%20UVRE/tools/zEdit%20v0.6.6.1/resources/app.asar/app/app.js:9316:15)
    at file:///F:/Skyrim%20UVRE/tools/zEdit%20v0.6.6.1/resources/app.asar/app/app.js:9362:13
    at Array.forEach (<anonymous>)
    at Object.runIntegrations (file:///F:/Skyrim%20UVRE/tools/zEdit%20v0.6.6.1/resources/app.asar/app/app.js:9360:40)
    at finalizeMerge (file:///F:/Skyrim%20UVRE/tools/zEdit%20v0.6.6.1/resources/app.asar/app/app.js:9181:33)
    at file:///F:/Skyrim%20UVRE/tools/zEdit%20v0.6.6.1/resources/app.asar/app/app.js:9212:13
    at file:///F:/Skyrim%20UVRE/tools/zEdit%20v0.6.6.1/resources/app.asar/app/app.js:9090:17
    at processQueue (F:\Skyrim UVRE\tools\zEdit v0.6.6.1\resources\app.asar\node_modules\angular\angular.js:18075:37

[merge_2022_02_21_16_48.txt](https://github.com/z-edit/zedit/files/8110997/merge_2022_02_21_16_48.txt)
)

**Comment by haajasparx** [comment]
Reportedly, there used to be a "Disable Mods" checkbox (underneath "Disable Plugins" in the general zMerge settings) and that fixed it for some people but now that checkbox is gone and I'm having the same problem, I can't build merges without being able to uncheck a box that no longer exists in zMerge. Does anyone know of another fix? My file paths are set correctly and the merge gets 95% done building before it fails with this same error message.
