### ISSUE TITLE
closing/exiting error

### ISSUE THREAD

**Issue by Yukimimiya** [matortheeternal/zedit#291]
Hi,
I'd launch zClean, check error, I tried to close windown, then i got following error.

![zEdit-Error](https://user-images.githubusercontent.com/2534035/207093532-1d861128-84a0-4939-bd28-4c955a8ddfbd.jpg)

Cleaning it selfs seem work fine.

Thanks!

**Comment by Yukimimiya** [comment]
Here is a app log.
```
[ERROR] TypeError: Expected argument 0 to be a number.
    at C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:110:26
    at helpers.GetHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\helpers.js:80:9)
    at Object.GetElementFile (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:109:20)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:4472:36
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6437:13
    at Object.WithHandles (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:26:24)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6344:19
    at Object.WithHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:19:24)
    at withNavmeshSiblings (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6343:15)
    at Object.withReplacementNavmesh (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6436:9)
[ERROR] TypeError: Expected argument 0 to be a number.
    at C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:110:26
    at helpers.GetHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\helpers.js:80:9)
    at Object.GetElementFile (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:109:20)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:4472:36
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6437:13
    at Object.WithHandles (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:26:24)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6344:19
    at Object.WithHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:19:24)
    at withNavmeshSiblings (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6343:15)
    at Object.withReplacementNavmesh (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6436:9)
[ERROR] TypeError: Expected argument 0 to be a number.
    at C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:110:26
    at helpers.GetHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\helpers.js:80:9)
    at Object.GetElementFile (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:109:20)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:4472:36
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6437:13
    at Object.WithHandles (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:26:24)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6344:19
    at Object.WithHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:19:24)
    at withNavmeshSiblings (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6343:15)
    at Object.withReplacementNavmesh (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6436:9)
[ERROR] TypeError: Expected argument 0 to be a number.
    at C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:110:26
    at helpers.GetHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\helpers.js:80:9)
    at Object.GetElementFile (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:109:20)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:4472:36
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6437:13
    at Object.WithHandles (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:26:24)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6344:19
    at Object.WithHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:19:24)
    at withNavmeshSiblings (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6343:15)
    at Object.withReplacementNavmesh (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6436:9)
[ERROR] TypeError: Expected argument 0 to be a number.
    at C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:110:26
    at helpers.GetHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\helpers.js:80:9)
    at Object.GetElementFile (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\elements.js:109:20)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:4472:36
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6437:13
    at Object.WithHandles (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:26:24)
    at file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6344:19
    at Object.WithHandle (C:\skyrim Tools\zEdit\resources\app.asar\node_modules\xelib\src\js\utils.js:19:24)
    at withNavmeshSiblings (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6343:15)
    at Object.withReplacementNavmesh (file:///C:/skyrim%20Tools/zEdit/resources/app.asar/app/app.js:6436:9)
```
Thanks.
