### ISSUE TITLE
AddScript() doesn't work

### ISSUE THREAD

**Issue by ProbablyManuel** [matortheeternal/zedit#82]
`AddScript()` always fails with the following error.

> [ERROR] Error: Failed to add array item to zPatch.esp\00016FFF: VMAD\Scripts, scriptName, DA05HircinesRingScript
Failed to resolve element at path: scriptName
    at helpers.Fail (C:\Users\user\Documents\Skyrim Tools\zEdit_Alpha_v0.4.3\resources\app.asar\node_modules\xelib\lib\helpers.js:58:15)
    at C:\Users\user\Documents\Skyrim Tools\zEdit_Alpha_v0.4.3\resources\app.asar\node_modules\xelib\lib\elements.js:149:21
    at helpers.GetHandle (C:\Users\user\Documents\Skyrim Tools\zEdit_Alpha_v0.4.3\resources\app.asar\node_modules\xelib\lib\helpers.js:75:9)
    at Object.AddArrayItem (C:\Users\user\Documents\Skyrim Tools\zEdit_Alpha_v0.4.3\resources\app.asar\node_modules\xelib\lib\elements.js:147:20)
    at Object.xelib.(anonymous function) [as AddScript] (C:\Users\user\Documents\Skyrim Tools\zEdit_Alpha_v0.4.3\resources\app.asar\node_modules\xelib\lib\common.js:20:37)
    at patch (eval at value (file:///C:/Users/user/Documents/Skyrim%20Tools/zEdit_Alpha_v0.4.3/resources/app.asar/app/app.js:632:18), <anonymous>:23:23)
    at eval (eval at value (file:///C:/Users/user/Documents/Skyrim%20Tools/zEdit_Alpha_v0.4.3/resources/app.asar/app/app.js:632:18), <anonymous>:551:17)
    at Array.forEach (<anonymous>)
    at patchRecords (eval at value (file:///C:/Users/user/Documents/Skyrim%20Tools/zEdit_Alpha_v0.4.3/resources/app.asar/app/app.js:632:18), <anonymous>:549:28)
    at filesToPatch.forEach.filename (eval at value (file:///C:/Users/user/Documents/Skyrim%20Tools/zEdit_Alpha_v0.4.3/resources/app.asar/app/app.js:632:18), <anonymous>:574:28)

~~`AddScriptProperty()` probably fails too.~~ Edit: No, works fine.

Example script (Doesn't do anything useful):
```Javascript
registerPatcher({
    info: info,
    gameModes: [xelib.gmTES5, xelib.gmSSE],
    settings: {
        label: 'Test Patcher',
        hidden: true
    },
    requiredFiles: [],
    getFilesToPatch: function(filenames) {
        return filenames;
    },
    execute: {
        process: [{
            load: function(plugin, helpers, settings, locals) {
                return {
                    signature: 'ARMO'
                }
            },
            patch: function(record, helpers, settings, locals) {
            	helpers.logMessage(xelib.LongName(record));
            	xelib.AddScript(record, 'DA05HircinesRingScript', 'Local');
            }
        }]
    }
});
```

**Comment by matortheeternal** [comment]
will look into this :+1:
